package wasmcloud:tools;

interface convert {
  component-to-wadm: func(component: list<u8>, name: string, version: string, description: string, image: string) -> result<string, string>;
}

world wit2wadm {
  export convert;
}
